# Generated by Django 4.0.6 on 2022-08-05 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Carocel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='brightpalace.png', upload_to='media/carocel')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=10)),
                ('town', models.CharField(max_length=15)),
                ('image1', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='media/brightpalace.png', force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[200, 150], upload_to='media/propertyImages')),
                ('image2', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='media/brightpalace.png', force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[200, 150], upload_to='media/propertyImages')),
                ('image3', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='media/brightpalace.png', force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[200, 150], upload_to='media/propertyImages')),
                ('description', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(to='core.amenity')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.district')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Propertys',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
