# Generated by Django 4.0.6 on 2022-08-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_property_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ref',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
