# Generated by Django 4.0.6 on 2022-08-11 12:08

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_property_options_remove_property_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carocel',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='media/brightpalace.png', force_format='JPEG', keep_meta=True, quality=95, scale=None, size=[1366, 768], upload_to='media/carocel'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image1',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='media/brightpalace.png', force_format='JPEG', keep_meta=True, quality=95, scale=None, size=[200, 150], upload_to='media/propertyImages'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image2',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='media/brightpalace.png', force_format='JPEG', keep_meta=True, quality=95, scale=None, size=[200, 150], upload_to='media/propertyImages'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image3',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='media/brightpalace.png', force_format='JPEG', keep_meta=True, quality=95, scale=None, size=[200, 150], upload_to='media/propertyImages'),
        ),
    ]
